const primaries2020Dates = [
  {
    state: '',
    stateAbbr: '',
    party: '',
    date: '2020-11-03',
    raceType: 'General',
    resultsNote: false,
  },
  {
    state: 'Iowa',
    stateAbbr: 'IA',
    party: 'Democratic',
    date: '2020-02-03',
    raceType: 'Caucuses',
    resultsNote: 'Vote totals are State Delegates Equivalents',
  },
  {
    state: 'Iowa',
    stateAbbr: 'IA',
    party: 'Republican',
    date: '2020-02-03',
    raceType: 'Caucuses',
    resultsNote: false,
  },
  {
    state: 'New Hampshire',
    stateAbbr: 'NH',
    party: 'Democratic',
    date: '2020-02-11',
    raceType: 'Primary',
    resultsNote: false,
  },
  {
    state: 'New Hampshire',
    stateAbbr: 'NH',
    party: 'Republican',
    date: '2020-02-11',
    raceType: 'Primary',
    resultsNote: false,
  },
  {
    state: 'Nevada',
    stateAbbr: 'NV',
    party: 'Democratic',
    date: '2020-02-22',
    raceType: 'Caucuses',
    resultsNote: 'Vote totals are county convention delegates',
  },
  {
    state: 'Nevada',
    stateAbbr: 'NV',
    party: 'Republican',
    date: '2020-02-25',
    raceType: 'Caucuses',
    resultsNote: 'No caucus scheduled',
    notHeld: true,
  },
  {
    state: 'South Carolina',
    stateAbbr: 'SC',
    party: 'Democratic',
    date: '2020-02-29',
    raceType: 'Primary',
    resultsNote: false,
  },
  {
    state: 'South Carolina',
    stateAbbr: 'SC',
    party: 'Republican',
    date: '2020-02-29',
    raceType: 'Primary',
    resultsNote: 'No primary scheduled',
    notHeld: true,
  },
  {
    state: 'Alabama',
    stateAbbr: 'AL',
    party: 'Democratic',
    date: '2020-03-03',
    raceType: 'Primary',
    resultsNote: false,
  },
  {
    state: 'Alabama',
    stateAbbr: 'AL',
    party: 'Republican',
    date: '2020-03-03',
    raceType: 'Primary',
    resultsNote: false,
  },
  {
    state: 'Arkansas',
    stateAbbr: 'AR',
    party: 'Democratic',
    date: '2020-03-03',
    raceType: 'Primary',
    resultsNote: false,
  },
  {
    state: 'Arkansas',
    stateAbbr: 'AR',
    party: 'Republican',
    date: '2020-03-03',
    raceType: 'Primary',
    resultsNote: false,
  },
  {
    state: 'California',
    stateAbbr: 'CA',
    party: 'Democratic',
    date: '2020-03-03',
    raceType: 'Primary',
    resultsNote: false,
  },
  {
    state: 'California',
    stateAbbr: 'CA',
    party: 'Republican',
    date: '2020-03-03',
    raceType: 'Primary',
    resultsNote: false,
  },
  {
    state: 'Colorado',
    stateAbbr: 'CO',
    party: 'Democratic',
    date: '2020-03-03',
    raceType: 'Primary',
    resultsNote: false,
  },
  {
    state: 'Colorado',
    stateAbbr: 'CO',
    party: 'Republican',
    date: '2020-03-03',
    raceType: 'Primary',
    resultsNote: false,
  },
  {
    state: 'Maine',
    stateAbbr: 'ME',
    party: 'Republican',
    date: '2020-03-03',
    raceType: 'Primary',
    resultsNote: false,
  },
  {
    state: 'Maine',
    stateAbbr: 'ME',
    party: 'Democratic',
    date: '2020-03-03',
    raceType: 'Primary',
    resultsNote: false,
  },
  {
    state: 'Massachusetts',
    stateAbbr: 'MA',
    party: 'Democratic',
    date: '2020-03-03',
    raceType: 'Primary',
    resultsNote: false,
  },
  {
    state: 'Massachusetts',
    stateAbbr: 'MA',
    party: 'Republican',
    date: '2020-03-03',
    raceType: 'Primary',
    resultsNote: false,
  },
  {
    state: 'Minnesota',
    stateAbbr: 'MN',
    party: 'Democratic',
    date: '2020-03-03',
    raceType: 'Caucuses',
    resultsNote: false,
  },
  {
    state: 'Minnesota',
    stateAbbr: 'MN',
    party: 'Republican',
    date: '2020-03-03',
    raceType: 'Caucuses',
    resultsNote: false,
  },
  {
    state: 'North Carolina',
    stateAbbr: 'NC',
    party: 'Democratic',
    date: '2020-03-03',
    raceType: 'Primary',
    resultsNote: false,
  },
  {
    state: 'North Carolina',
    stateAbbr: 'NC',
    party: 'Republican',
    date: '2020-03-03',
    raceType: 'Primary',
    resultsNote: false,
  },
  {
    state: 'Oklahoma',
    stateAbbr: 'OK',
    party: 'Democratic',
    date: '2020-03-03',
    raceType: 'Primary',
    resultsNote: false,
  },
  {
    state: 'Oklahoma',
    stateAbbr: 'OK',
    party: 'Republican',
    date: '2020-03-03',
    raceType: 'Primary',
    resultsNote: false,
  },
  {
    state: 'Tennessee',
    stateAbbr: 'TN',
    party: 'Democratic',
    date: '2020-03-03',
    raceType: 'Primary',
    resultsNote: false,
  },
  {
    state: 'Tennessee',
    stateAbbr: 'TN',
    party: 'Republican',
    date: '2020-03-03',
    raceType: 'Primary',
    resultsNote: false,
  },
  {
    state: 'Texas',
    stateAbbr: 'TX',
    party: 'Democratic',
    date: '2020-03-03',
    raceType: 'Primary',
    resultsNote: false,
  },
  {
    state: 'Texas',
    stateAbbr: 'TX',
    party: 'Republican',
    date: '2020-03-03',
    raceType: 'Primary',
    resultsNote: false,
  },
  {
    state: 'Utah',
    stateAbbr: 'UT',
    party: 'Democratic',
    date: '2020-03-03',
    raceType: 'Caucuses',
    resultsNote: false,
  },
  {
    state: 'Utah',
    stateAbbr: 'UT',
    party: 'Republican',
    date: '2020-03-03',
    raceType: 'Caucuses',
    resultsNote: false,
  },
  {
    state: 'Vermont',
    stateAbbr: 'VT',
    party: 'Democratic',
    date: '2020-03-03',
    raceType: 'Primary',
    resultsNote: false,
  },
  {
    state: 'Vermont',
    stateAbbr: 'VT',
    party: 'Republican',
    date: '2020-03-03',
    raceType: 'Primary',
    resultsNote: false,
  },
  {
    state: 'Virginia',
    stateAbbr: 'VA',
    party: 'Democratic',
    date: '2020-03-03',
    raceType: 'Primary',
    resultsNote: false,
  },
  {
    state: 'Virginia',
    stateAbbr: 'VA',
    party: 'Republican',
    date: '2020-03-03',
    raceType: 'Primary',
    resultsNote: 'No primary scheduled',
    notHeld: true,
  },
  {
    state: 'Idaho',
    stateAbbr: 'ID',
    party: 'Republican',
    date: '2020-03-10',
    raceType: 'Primary',
    resultsNote: false,
  },
  {
    state: 'Idaho',
    stateAbbr: 'ID',
    party: 'Democratic',
    date: '2020-03-10',
    raceType: 'Caucuses',
    resultsNote: false,
  },
  {
    state: 'Michigan',
    stateAbbr: 'MI',
    party: 'Democratic',
    date: '2020-03-11',
    raceType: 'Primary',
    resultsNote: false,
  },
  {
    state: 'Michigan',
    stateAbbr: 'MI',
    party: 'Republican',
    date: '2020-03-11',
    raceType: 'Primary',
    resultsNote: false,
  },
  {
    state: 'Mississippi',
    stateAbbr: 'MS',
    party: 'Democratic',
    date: '2020-03-10',
    raceType: 'Primary',
    resultsNote: false,
  },
  {
    state: 'Mississippi',
    stateAbbr: 'MS',
    party: 'Republican',
    date: '2020-03-10',
    raceType: 'Primary',
    resultsNote: false,
  },
  {
    state: 'Missouri',
    stateAbbr: 'MO',
    party: 'Democratic',
    date: '2020-03-10',
    raceType: 'Primary',
    resultsNote: false,
  },
  {
    state: 'Missouri',
    stateAbbr: 'MO',
    party: 'Republican',
    date: '2020-03-10',
    raceType: 'Primary',
    resultsNote: false,
  },
  {
    state: 'North Dakota',
    stateAbbr: 'ND',
    party: 'Democratic',
    date: '2020-03-10',
    raceType: 'Caucuses',
    resultsNote: false,
  },
  {
    state: 'North Dakota',
    stateAbbr: 'ND',
    party: 'Republican',
    date: '2020-03-10',
    raceType: 'Caucuses',
    resultsNote: false,
  },
  {
    state: 'Washington',
    stateAbbr: 'WA',
    party: 'Democratic',
    date: '2020-03-10',
    raceType: 'Primary',
    resultsNote: false,
  },
  {
    state: 'Washington',
    stateAbbr: 'WA',
    party: 'Republican',
    date: '2020-03-10',
    raceType: 'Primary',
    resultsNote: false,
  },
  {
    state: 'Hawaii',
    stateAbbr: 'HI',
    party: 'Republican',
    date: '2020-03-10',
    raceType: 'Caucuses',
    resultsNote: 'No caucus scheduled',
    notHeld: true,
  },
  {
    state: 'Arizona',
    stateAbbr: 'AZ',
    party: 'Democratic',
    date: '2020-03-17',
    raceType: 'Primary',
    resultsNote: false,
  },
  {
    state: 'Arizona',
    stateAbbr: 'AZ',
    party: 'Republican',
    date: '2020-03-17',
    raceType: 'Primary',
    resultsNote: 'No primary scheduled',
    notHeld: true,
  },
  {
    state: 'Florida',
    stateAbbr: 'FL',
    party: 'Democratic',
    date: '2020-03-17',
    raceType: 'Primary',
    resultsNote: false,
  },
  {
    state: 'Florida',
    stateAbbr: 'FL',
    party: 'Republican',
    date: '2020-03-17',
    raceType: 'Primary',
    resultsNote: false,
  },
  {
    state: 'Illinois',
    stateAbbr: 'IL',
    party: 'Democratic',
    date: '2020-03-17',
    raceType: 'Primary',
    resultsNote: false,
  },
  {
    state: 'Illinois',
    stateAbbr: 'IL',
    party: 'Republican',
    date: '2020-03-17',
    raceType: 'Primary',
    resultsNote: false,
  },
  {
    state: 'Ohio',
    stateAbbr: 'OH',
    party: 'Democratic',
    date: '2020-03-17',
    raceType: 'Primary',
    resultsNote: false,
  },
  {
    state: 'Ohio',
    stateAbbr: 'OH',
    party: 'Republican',
    date: '2020-03-17',
    raceType: 'Primary',
    resultsNote: false,
  },
  {
    state: 'Georgia',
    stateAbbr: 'GA',
    party: 'Democratic',
    date: '2020-03-24',
    raceType: 'Primary',
    resultsNote: false,
  },
  {
    state: 'Georgia',
    stateAbbr: 'GA',
    party: 'Republican',
    date: '2020-03-24',
    raceType: 'Primary',
    resultsNote: false,
  },
  {
    state: 'Alaska',
    stateAbbr: 'AK',
    party: 'Democratic',
    date: '2020-04-04',
    raceType: 'Primary',
    resultsNote: false,
  },
  {
    state: 'Alaska',
    stateAbbr: 'AK',
    party: 'Republican',
    date: '2020-04-04',
    raceType: 'Caucuses',
    resultsNote: 'No caucus scheduled',
    notHeld: true,
  },
  {
    state: 'Hawaii',
    stateAbbr: 'HI',
    party: 'Democratic',
    date: '2020-04-04',
    raceType: 'Primary',
    resultsNote: false,
  },
  {
    state: 'Louisiana',
    stateAbbr: 'LA',
    party: 'Democratic',
    date: '2020-04-04',
    raceType: 'Primary',
    resultsNote: false,
  },
  {
    state: 'Louisiana',
    stateAbbr: 'LA',
    party: 'Republican',
    date: '2020-04-04',
    raceType: 'Primary',
    resultsNote: false,
  },
  {
    state: 'Wyoming',
    stateAbbr: 'WY',
    party: 'Democratic',
    date: '2020-04-04',
    raceType: 'Caucuses',
    resultsNote: false,
  },
  {
    state: 'Wyoming',
    stateAbbr: 'WY',
    party: 'Republican',
    date: '2020-04-04',
    raceType: 'Caucuses',
    resultsNote: 'No caucus scheduled',
    notHeld: true,
  },
  {
    state: 'Wisconsin',
    stateAbbr: 'WI',
    party: 'Democratic',
    date: '2020-04-07',
    raceType: 'Primary',
    resultsNote: false,
  },
  {
    state: 'Wisconsin',
    stateAbbr: 'WI',
    party: 'Republican',
    date: '2020-04-07',
    raceType: 'Primary',
    resultsNote: false,
  },
  {
    state: 'Connecticut',
    stateAbbr: 'CT',
    party: 'Democratic',
    date: '2020-04-28',
    raceType: 'Primary',
    resultsNote: false,
  },
  {
    state: 'Connecticut',
    stateAbbr: 'CT',
    party: 'Republican',
    date: '2020-04-28',
    raceType: 'Primary',
    resultsNote: false,
  },
  {
    state: 'Delaware',
    stateAbbr: 'DE',
    party: 'Democratic',
    date: '2020-04-28',
    raceType: 'Primary',
    resultsNote: false,
  },
  {
    state: 'Delaware',
    stateAbbr: 'DE',
    party: 'Republican',
    date: '2020-04-28',
    raceType: 'Primary',
    resultsNote: false,
  },
  {
    state: 'Maryland',
    stateAbbr: 'MD',
    party: 'Democratic',
    date: '2020-04-28',
    raceType: 'Primary',
    resultsNote: false,
  },
  {
    state: 'Maryland',
    stateAbbr: 'MD',
    party: 'Republican',
    date: '2020-04-28',
    raceType: 'Primary',
    resultsNote: false,
  },
  {
    state: 'New York',
    stateAbbr: 'NY',
    party: 'Democratic',
    date: '2020-04-28',
    raceType: 'Primary',
    resultsNote: false,
  },
  {
    state: 'New York',
    stateAbbr: 'NY',
    party: 'Republican',
    date: '2020-04-28',
    raceType: 'Primary',
    resultsNote: false,
  },
  {
    state: 'Pennsylvania',
    stateAbbr: 'PA',
    party: 'Democratic',
    date: '2020-04-28',
    raceType: 'Primary',
    resultsNote: false,
  },
  {
    state: 'Pennsylvania',
    stateAbbr: 'PA',
    party: 'Republican',
    date: '2020-04-28',
    raceType: 'Primary',
    resultsNote: false,
  },
  {
    state: 'Rhode Island',
    stateAbbr: 'RI',
    party: 'Democratic',
    date: '2020-04-28',
    raceType: 'Primary',
    resultsNote: false,
  },
  {
    state: 'Rhode Island',
    stateAbbr: 'RI',
    party: 'Republican',
    date: '2020-04-28',
    raceType: 'Primary',
    resultsNote: false,
  },
  {
    state: 'Kansas',
    stateAbbr: 'KS',
    party: 'Democratic',
    date: '2020-05-02',
    raceType: 'Caucuses',
    resultsNote: false,
  },
  {
    state: 'Kansas',
    stateAbbr: 'KS',
    party: 'Republican',
    date: '2020-05-02',
    raceType: 'Caucuses',
    resultsNote: false,
  },
  {
    state: 'Indiana',
    stateAbbr: 'IN',
    party: 'Democratic',
    date: '2020-05-05',
    raceType: 'Primary',
    resultsNote: false,
  },
  {
    state: 'Indiana',
    stateAbbr: 'IN',
    party: 'Republican',
    date: '2020-05-05',
    raceType: 'Primary',
    resultsNote: false,
  },
  {
    state: 'Nebraska',
    stateAbbr: 'NE',
    party: 'Republican',
    date: '2020-05-12',
    raceType: 'Primary',
    resultsNote: false,
  },
  {
    state: 'Nebraska',
    stateAbbr: 'NE',
    party: 'Democratic',
    date: '2020-05-12',
    raceType: 'Primary',
    resultsNote: false,
  },
  {
    state: 'West Virginia',
    stateAbbr: 'WV',
    party: 'Democratic',
    date: '2020-05-12',
    raceType: 'Primary',
    resultsNote: false,
  },
  {
    state: 'West Virginia',
    stateAbbr: 'WV',
    party: 'Republican',
    date: '2020-05-12',
    raceType: 'Primary',
    resultsNote: false,
  },
  {
    state: 'Kentucky',
    stateAbbr: 'KY',
    party: 'Democratic',
    date: '2020-05-19',
    raceType: 'Primary',
    resultsNote: false,
  },
  {
    state: 'Kentucky',
    stateAbbr: 'KY',
    party: 'Republican',
    date: '2020-05-19',
    raceType: 'Primary',
    resultsNote: false,
  },
  {
    state: 'Oregon',
    stateAbbr: 'OR',
    party: 'Democratic',
    date: '2020-05-19',
    raceType: 'Primary',
    resultsNote: false,
  },
  {
    state: 'Oregon',
    stateAbbr: 'OR',
    party: 'Republican',
    date: '2020-05-19',
    raceType: 'Primary',
    resultsNote: false,
  },
  {
    state: 'District of Columbia',
    stateAbbr: 'DC',
    party: 'Republican',
    date: '2020-06-02',
    raceType: 'Primary',
    resultsNote: false,
  },
  {
    state: 'District of Columbia',
    stateAbbr: 'DC',
    party: 'Democratic',
    date: '2020-06-02',
    raceType: 'Primary',
    resultsNote: false,
  },
  {
    state: 'Montana',
    stateAbbr: 'MT',
    party: 'Democratic',
    date: '2020-06-02',
    raceType: 'Primary',
    resultsNote: false,
  },
  {
    state: 'Montana',
    stateAbbr: 'MT',
    party: 'Republican',
    date: '2020-06-02',
    raceType: 'Primary',
    resultsNote: false,
  },
  {
    state: 'New Jersey',
    stateAbbr: 'NJ',
    party: 'Democratic',
    date: '2020-06-02',
    raceType: 'Primary',
    resultsNote: false,
  },
  {
    state: 'New Jersey',
    stateAbbr: 'NJ',
    party: 'Republican',
    date: '2020-06-02',
    raceType: 'Primary',
    resultsNote: false,
  },
  {
    state: 'New Mexico',
    stateAbbr: 'NM',
    party: 'Democratic',
    date: '2020-06-02',
    raceType: 'Primary',
    resultsNote: false,
  },
  {
    state: 'New Mexico',
    stateAbbr: 'NM',
    party: 'Republican',
    date: '2020-06-02',
    raceType: 'Primary',
    resultsNote: false,
  },
  {
    state: 'South Dakota',
    stateAbbr: 'SD',
    party: 'Democratic',
    date: '2020-06-02',
    raceType: 'Primary',
    resultsNote: false,
  },
  {
    state: 'South Dakota',
    stateAbbr: 'SD',
    party: 'Republican',
    date: '2020-06-02',
    raceType: 'Primary',
    resultsNote: false,
  },
];

export default primaries2020Dates;
